name: helm-actions-testing

on:
    push:
        branches:
            - main

jobs:
    helm-actions-testing:
        runs-on: ubuntu-latest

        steps:
            - name: Helm installation
              run: |                  
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version

            - name: Helm template and git--push
              run: |
                  git clone https://github.com/Akashpawar11/pingpong1.git
                  cd pingpong1
                  git config user.name "Akash Pawar"
                  git config user.email "akash.pawar@wohlig.com"
                  yq e '.replicaCount = "6"' -i helm-chart/values.yaml
                  cat ./helm-chart/values.yaml
                  helm template uat-env ./helm-chart > manifests.yaml
                  cat manifests.yaml
                  git add .
                  git commit -m "commit through pipeline"
                  git push origin main