name: api-production

on:
    # Trigger the workflow on push,
    # but only for the production branch
    push:
        branches:
            - main

jobs:
    api-production:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone
              run: |
                  git clone https://github.com/Akashpawar11/pingpong1.git
                  cd pingpong1/helm-chart
                  git config --global user.name "wohligakash"
                  git config --global user.email "akash.pawar@wohlig.com"
                  git config --global user.password "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"
                  yq e '.replicaCount = "6"' -i values.yaml
                  git add .
                  git commit -m "updating newer image"
                  git push main main