name: api-production

on:
    # Trigger the workflow on push,
    # but only for the production branch
    push:
        branches:
            - main

jobs:
    api-production:
        runs-on: ubuntu-latest

        steps:
            - name: Build the Docker image
              run: |
                  git clone https://Akashpawar11@github.com/pingpong1
                  cd helm-chart
                  git checkout main
                  git config user.name "wohligakash"
                  git config user.email "akash.pawar@wohlig.com"
                  yq e '.replicaCount = "6"' -i values.yaml
                  git add .
                  git commit -m "updating newer image"
                  git push --set-upstream origin main
            
