name: helm-actions-testing

on:
    push:
        branches:
            - main

jobs:
    helm-actions-testing:
        runs-on: ubuntu-latest

        steps:
            - name: Helm actions
              run: |
                  git clone https://github.com/Akashpawar11/pingpong1.git
                  cd pingpong1
                  git config --global user.name "Akashpawar11"
                  git config --global user.email "akashpawar1103@gmail.com"
                  yq e '.replicaCount = "6"' -i helm-chart/values.yaml
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version
                  helm template uat-env ./helm-chart > manifests.yaml
                  cat manifests.yaml

                  git add .
                  git commit -m "updating newer image"
                  git push main main
