name: api-production

on:
    # Trigger the workflow on push,
    # but only for the production branch
    push:
        branches:
            - main

jobs:
    api-production:
        runs-on: ubuntu-latest

        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - uses: actions/checkout@v2

            - name: Build the Docker image
              run: |
                  git clone https://Akashpawar11@github.com/pingpong1
                  cd helm-chart
                  git checkout main
                  git config user.name "wohligakash"
                  git config user.email "akash.pawar@wohlig.com"
                  yq e '.replicaCount = "6"' -i values.yaml
                  git add .
                  git commit -m "updating newer image"
                  git push --set-upstream origin main
            
