name: api-production

on:
    # Trigger the workflow on push,
    # but only for the production branch
    push:
        branches:
            - main

jobs:
    api-production:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone
              run: |
                  git clone git@github.com:Akashpawar11/pingpong1.git
                  cd pingpong1/helm-chart
                  git config user.name "wohligakash"
                  git config user.email "akash.pawar@wohlig.com"
                  yq e '.replicaCount = "2"' -i values.yaml
                  git add .
                  git commit -m "updating newer image"
                  git push origin main