name: api-production

on:
    push:
        branches:
            - main

jobs:
    api-production:
        runs-on: ubuntu-latest

        steps:
            - name: Helm actions
              run: |
                  git clone https://github.com/Akashpawar11/pingpong1.git
                  git config --global user.name "wohligakash"
                  git config --global user.email "akash.pawar@wohlig.com"
                  git config --global user.password "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"
                  yq e '.replicaCount = "6"' -i .pingpong1/helm-chart/values.yaml
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version
                  helm template uat-env ./pingpong1/helm-chart > manifests.yaml
                  cat manifests.yaml

